### ISSUE TITLE
Horizontal ScrollBar Visible

### ISSUE THREAD

**Issue by trupakufi** [EufranioDiogo/a-simple-sample-service-page#1]
Opaaaa, e a]i mano?? Beleza??

Eu dei uma olhada no seu sample service page, e a cena ta fire, muito foda, parabéns, mas se liga aí no scroll horizontal aparecendo na tela.

@EufranioDiogo Olha ae mano.

**Comment by EufranioDiogo** [comment]
Obrigado pela issue Varela, e desculpas pela demora lol tive alguns problemas nos últimos dias, mas vou verificar ela, resolver e dou o feedback o mais rápido possível.

@mariovarela99 Abraços

**Comment by EufranioDiogo** [comment]
Hi @mariovarela99, mais uma vez obrigado pela sua issue, acabei de resolver ela agora, gostaria de receber o teu feedback antes de fechar a issue.

Mas desde já obrigado e bom coding para ti.

**Comment by trupakufi** [comment]
> Obrigado pela issue Varela, e desculpas pela demora lol tive alguns problemas nos últimos dias, mas vou verificar ela, resolver e dou o feedback o mais rápido possível.
> 
> @mariovarela99 Abraços

@EufranioDiogo 
Não tem problema não. Estamos aqui para isso.

**Comment by trupakufi** [comment]
> Hi @mariovarela99, mais uma vez obrigado pela sua issue, acabei de resolver ela agora, gostaria de receber o teu feedback antes de fechar a issue.
> 
> Mas desde já obrigado e bom coding para ti.

Não tem de quê, acabei de ver que ta tudo melhor do que antes, ta muito bom agora muito bom.

**Comment by EufranioDiogo** [comment]
Rsrsrsrs que bom que você gostou, fico feliz por isso.

E obrigado pelo tempo e atenção prestada meu caro @mariovarela99 , abraços.

**Comment by trupakufi** [comment]
> Rsrsrsrs que bom que você gostou, fico feliz por isso.
> 
> E obrigado pelo tempo e atenção prestada meu caro @mariovarela99 , abraços.

Tamos juntos.
